### ISSUE TITLE
Crash on startup(yes i did disable iris)

### ISSUE THREAD

**Issue by bunger1** [pixeldreamstudios/FantasyMinecraft#10]
### Describe the Bug

just crashes on startup every time

### Reproduction Steps

start the instance

### Crash-logs

[crash-2023-04-08_21.34.06-client.txt](https://github.com/pixeldreamstudios/FantasyMinecraft/files/11184610/crash-2023-04-08_21.34.06-client.txt)

### Modpack Version

1.19.2

**Comment by kyber-6** [comment]
REI seems like the culprit, although it shouldn't be. Try repairing your profile or launching from a different launcher.
