### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by spooly87** [pixeldreamstudios/FantasyMinecraft#11]
### Describe the Bug

can't get the game to load at all, it gets to the end of the load bar on the loading screen and immediately brings up the mincraft launcher with exit code 1

### Reproduction Steps

 any time i try to play minecraft fantasy, does not crash with any other mod packs on the curseforge app

### Modpack Version

v10.6

**Comment by kyber-6** [comment]
We’ll need a crash report although you probably need to remove the iris mod.
