### ISSUE TITLE
Ascension LevelZ Quests and Quests in General.

### ISSUE THREAD

**Issue by IcyJalapeno** [pixeldreamstudios/FantasyMinecraft#13]
### Describe the Bug

Farming Up: All 3 Farming Objective met, Received +3 Farming instead of +3 Stamina according to the quest reward marked as Stamina.

Stamina Up: All 3 Stamina Object met: Not receiving any reward at all. 

I would advise double checking the rest of the quests in the modpack.

The Ultimate Miner ->  Break x2 Diamond Ore, refused to activate until I mined diamond ore, with a Ironwood pickaxe.

Edit *Had to leave the nether for the stamina quest to finally trigger. What? Stamina still didn't add to the total on the leveling screen. Had 10, quest completed, still 10.

### Reproduction Steps

Complete the Challenges and try to receive the rewards.

### Modpack Version

10.7

**Comment by kyber-6** [comment]
The staff that made these quests will look into it, thanks for reporting it.

**Comment by KevzCz** [comment]
I fixed the Farming stat up’s wrong reward name
The command for stamina up was /playerstats @p add Stamina, but it had to be ‘stamina’ so i fixed it.
The quests that checks your progress can sometimes not count your progress. I tested everything and it seemed to worked fine. I’m unsure how to fix this problem but i’ll keep an eye on it.

**Comment by IcyJalapeno** [comment]
Could you guys double check quest that require enchanted books as turn ins? Can't submit them for turns in or they're not being detected.  

Ultimate Miner -> Jackhammer and Diamond Pickaxe Quests. *Both The Branching Pathway from Raw Ori
Ascension LevelZ -> Enchanted Book for Mining Up

**Comment by KevzCz** [comment]
Alright I finished fixing it. Thank you for your help :Đ

**Comment by IcyJalapeno** [comment]
Not a problem, happy to help. Is there a server command to auto-complete these quests in the meantime? So my buddies and myself can proceed with the rewards.

**Comment by kyber-6** [comment]
> Not a problem, happy to help. Is there a server command to auto-complete these quests in the meantime? So my buddies and myself can proceed with the rewards.

Go into quest editing mode by running `/ftbquests editing_mode true`
