### ISSUE TITLE
Marium's Soulslike Weaponey conflicting with Biome Makeover mod

### ISSUE THREAD

**Issue by ShyGuyKaii** [pixeldreamstudios/FantasyMinecraft#15]
### Describe the Bug

After I defeated the Old Champion from Marium's Soulslike Weaponry mod, the 'Lord Soul' that was supposed to drop disappeared and was replaced with the item 'Piece of Dark Lord Soul' from the Biome Makeover mod. I tested this out multiple times to make sure the Lord Soul was indeed dropping. It appears on the ground as a drop (the second screenshot below demonstrates this) but as soon as I pick it up, it is replaced with the Piece of Dark Lord Soul. When recreating in creative, the game crashes when forcing the Lord Soul into my inventory. 

### Reproduction Steps

1. Give yourself Lord Soul in Creative (any Lord Soul works) 
2. Place in Hotbar 
3. the game will notify you with "you can't seem to get a grasp of this soul...but it still lingers around you"
4. the game will remove the item from your inventory and replace it with the item 'Piece of Dark Lord Soul' that is from the Biome Makeover mod. However, I think that may be a mistake as the item Piece of Dark Lord Soul doesn't even show up in Roughly Enough items. Couldn't even find anything related to it on Google
* For singleplayer, steps are the same except step 3 does not happen 

### Screenshots

![2023-04-16_21 15 09](https://user-images.githubusercontent.com/130943704/232356115-b6d522d0-f9dd-4e47-914e-bbbad7f69ed9.png)

![2023-04-16_21 19 12](https://user-images.githubusercontent.com/130943704/232356486-497aea0a-bab6-452d-b37c-997906ab0659.png)

### Modpack Version

v10.7

**Comment by KevzCz** [comment]
Check the Marium’s soulslike weaponry chapter in ftbquests

**Comment by ShyGuyKaii** [comment]
> 

Unfortunately, the chapter doesn't fix anything. No matter what, the souls turn into obsolete "Piece of the Lord Soul". I would like to know if anyone else is having this issue or if it's just me.

**Comment by KevzCz** [comment]
It has been changed in the update 11.0 it will now drop the lord soul item but you still have to craft through weapons through the chapter in quests

**Comment by ShyGuyKaii** [comment]
Yes, I noticed the issue was addressed in the latest update! Thank you so much!
