### ISSUE TITLE
wildlife is drowning out the spawns from every other mod including ones necessary to use MAGIC

### ISSUE THREAD

**Issue by Lvalentine1010** [pixeldreamstudios/FantasyMinecraft#16]
### Describe the Bug

wildlife is drowning out the spawns from every other mod including ones necessary to use MAGIC please remove it for the love of lilith

### Reproduction Steps

literally find one bewitchment snake for me bestie or a base game rabbit do it

### Modpack Version

current

**Comment by IcyJalapeno** [comment]
I will agree. Trying to find base minecraft rabbits in the desert in a nightmare of a chore, to attempt to get a rabbit's foot drop. I honestly had to remove so many mods that are nothing but creatures. For (1) to have actual good fps. (2) my minimap not the littered with dots everywhere. (3) it dealt with some of the sudden extreme server lag and rubber banding, I had issues with all of them turn on.

**Comment by kyber-6** [comment]
I will remove the Wildlife mod in the next update.
