### ISSUE TITLE
Naga Head crashed game

### ISSUE THREAD

**Issue by xjreyes7** [pixeldreamstudios/FantasyMinecraft#17]
### Describe the Bug

I Defeated the Naga and put the head on my character, as soon as I did this my game froze and then crashed. 

I now cannot play as I load back up and my game freezes immediately before I can take the head off. 

### Modpack Version

v10.7

**Comment by KevzCz** [comment]
This is an issue with certain 3D items when put on. Version 11.0 of the modpack has removed Twilight Forest and Arclight because of frequent crashes because of equipable items. There aren't really any ways to fix it in v10.7 except removing the mod.
