### ISSUE TITLE
Can't use Origin Abilities

### ISSUE THREAD

**Issue by deadpool24135** [pixeldreamstudios/FantasyMinecraft#2]
### Describe the Bug

When selecting an Origin can't use their keybind abilities.

### Reproduction Steps

Select origin, press keybind for ability.

### Modpack Version

v2.0.0

**Comment by deadpool24135** [comment]
Just found out changing the keybind from the default (G) fixes the issue.

**Comment by kyber-6** [comment]
There must be a conflict with another mod. I will change the default keybind in the next update. Thanks for pointing this out!
