### ISSUE TITLE
damage bug

### ISSUE THREAD

**Issue by Nion6676** [pixeldreamstudios/FantasyMinecraft#20]
### Describe the Bug

hi, I started a fantasy minecraft server with my friends but none of us can receibe damage from any source, I tried everything related to gamerule commands and stuff like that but the bug is still there, Im using v11.3. is it something related to the modpack?

### Modpack Version

v11.3

**Comment by kyber-6** [comment]
The issue you are having is probably related to tick lag. When you break something does it actually break and drop something?

**Comment by Nion6676** [comment]
yes, and also when you kill a mob it drops the items and everything is working fine, the only problem is that we can't take damage, and i don't think it is something related to tick lag because i can stay afk next to a zombie for an hour and i would not lose health.

**Comment by Nion6676** [comment]
don't worry i just resolved it, idk why but somehow we didn't have a hitbox, so I reinstaled better combat and it worked somehow.
