### ISSUE TITLE
Adventurez and Bosses of Mass Destruction

### ISSUE THREAD

**Issue by sherpascott** [pixeldreamstudios/FantasyMinecraft#3]
### Is your feature request related to a problem? Please describe.

I was just hoping to have those mods added and wondering if there’s a compatibility issue?

### Describe the solution you'd like

I was just curious. Thx!

**Comment by kyber-6** [comment]
There shouldn't be a compatibility issue. I'm actually adding those in the next update, thanks for the recommendation.

**Comment by sherpascott** [comment]
Sweet! Can’t wait.
