### ISSUE TITLE
No Vanilla and others sounds?

### ISSUE THREAD

**Issue by DarkFenixRS** [pixeldreamstudios/FantasyMinecraft#5]
### Describe the Bug

I just download modpack in Curse but...Some Vanilla Sounds are missing...

### Modpack Version

9.2.3

**Comment by pixeldreamstudios** [comment]
Try restarting the modpack.

**Comment by DarkFenixRS** [comment]
> 

I try but doest resolve! Now I'will try turn off "Sounds mods" and test...

**Comment by pixeldreamstudios** [comment]
Great! This shouldn't be an issue though; something probably went wrong during the installation. As an alternative fix for anyone who may see this, try re-installing the modpack.

**Comment by DarkFenixRS** [comment]
> Great! This shouldn't be an issue though; something probably went wrong during the installation. As an alternative fix for anyone who may see this, try re-installing the modpack.

i reinstaled and doest work btw

**Comment by pixeldreamstudios** [comment]
> > Great! This shouldn't be an issue though; something probably went wrong during the installation. As an alternative fix for anyone who may see this, try re-installing the modpack.
> 
> i reinstaled and doest work btw

Strange, can you tell me what you did exactly to fix it?
