### ISSUE TITLE
No inventory sorting or strip mining aids.

### ISSUE THREAD

**Issue by LvsrsRedDragon** [pixeldreamstudios/FantasyMinecraft#7]
### Is your feature request related to a problem? Please describe.

Okay. So, this is probably my favourite modpack with a medieval vibe RN. It's really good! However, it has one tiny flaw: Inventory Management. There is no "sort Inventory" system, and much less something like "tom's simple storage".  Also, there is no way to better strip-mine/break blocks quickly aside from Tree Chopper.

### Describe the solution you'd like

I suggest adding Tom's Simple Storage or slotlink (there is a create resourcepack avaiable for TSS, if you want to keep the medieval appearence), it would really help players organize their inventories later in the game. For early game, an inventory sotrer would also be great. 
About the second issue, have you thought of vanilla excavators and hammers? Those are really nice for caving, since you've decided not to include veinmining.

**Comment by kyber-6** [comment]
Glad to hear you’re enjoying the modpack. We’ll consider your recommendations, especially the one about Tom’s Simple Storage.
